### ISSUE TITLE
Manufacturing metrics

### ISSUE THREAD

**Issue by smartalecH** [invrs-io/gym#40]
Similar to posing challenges that maximize some arbitrary performance metric, it would be useful to establish manufacturability metrics (and post a leaderboard for approaches there)

**Comment by mfschubert** [comment]
Yes, I agree some form of leaderboard would be very useful. This could be based on the [imageruler](https://github.com/NanoComp/imageruler/tree/main/imageruler), although one would need to think carefully e.g. about how to handle designs that are not quite binary. It would be useful to have a dataset of designs created by a variety of approaches, which could then be used to stress test the manufacturability metrics.

**Comment by mfschubert** [comment]
The leaderboard with manufacturing metrics is now live, here:

docs: https://invrs-io.github.io/leaderboard/readme.html
repo: https://github.com/invrs-io/leaderboard
